---

- name: Add physical interfaces to the WAN-peer Interface Profile (side-a)
  aci_rest:
    host: "{{ inventory_hostname }}"
    validate_certs: False
    username: "{{ username }}"
    password: "{{ password }}"
    path: /api/node/mo/uni/infra/accportprof-{{ name_prefix }}_wan_intprof/hports-eth{{ item.module }}-{{ item.int_num }}-typ-range.json
    method: post
    content: "{{ lookup('template', 'acc_prof_int_selector.json.j2') }}"
  loop: "{{ wan_peer.nodes.side_a.interfaces }}"
  delegate_to: localhost 

- name: Add physical interfaces to the WAN-peer Interface Profile (side-b)
  aci_rest:
    host: "{{ inventory_hostname }}"
    validate_certs: False
    username: "{{ username }}"
    password: "{{ password }}"
    path: /api/node/mo/uni/infra/accportprof-{{ name_prefix }}_wan_intprof/hports-eth{{ item.module }}-{{ item.int_num }}-typ-range.json
    method: post
    content: "{{ lookup('template', 'acc_prof_int_selector.json.j2') }}"
  loop: "{{ wan_peer.nodes.side_b.interfaces }}"
  delegate_to: localhost 

